# -*- coding: utf-8 -*-
# vim: ft=yaml
---
## Machine config
os: 'linux'
arch: 'amd64'
dist: 'bionic'

## Language and cache config
language: 'ruby'
cache: 'bundler'

## Services config
services:
  - docker

## Require sudo 
sudo: 'required'

# Make sure the instances listed below match up with
# the `platforms` defined in `kitchen.yml`
# NOTE: Please try to select up to six instances that add some meaningful
#       testing of the formula's behaviour. If possible, try to refrain from
#       the classical "chosing all the instances because I want to test on
#       another/all distro/s" trap: it will just add time to the testing (see
#       the discussion on #121).  As an example, the set chosen below covers
#       the most used distros families, systemd and non-systemd and the latest
#       three supported Saltstack versions with python2 and 3.
#       As for `kitchen.yml`, that should still contain all of the platforms,
#       to allow for comprehensive local testing
#       Ref: https://github.com/saltstack-formulas/template-formula/issues/118
#       Ref: https://github.com/saltstack-formulas/template-formula/issues/121
  matrix:
    - INSTANCE: default-ubuntu-1804-master-py3
    # - INSTANCE: default-centos-8-master-py3
    # - INSTANCE: default-ubuntu-1804-3000-3-py3
    # - INSTANCE: default-ubuntu-1804-2019-2-py3
    - INSTANCE: default-centos-8-3000-3-py3
    # - INSTANCE: default-centos-7-3000-3-py3
    # - INSTANCE: default-centos-8-2019-2-py3
    - INSTANCE: default-centos-7-2019-2-py3

before_install:
  - bundle install

script:
  - bin/kitchen verify ${INSTANCE}
